# Site settings
name: Less Or More
email: aric.eric@outlook.com
author: Freud Kang
url: https://lounlay.github.io
resume_site: ''
github: https://github.com/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Lounlay

# Build settings
markdown: kramdown


# Comments 评论功能
comments:

  gitalk: true
  gitalk_clientID: '674a770a0e49b23f03b6'
  gitalk_Secret: 'f5f940679ef8ad11f25a2de5a02cbc5946e4bc5a'
  gitalk_repo: 'lounlay.github.io'
  gitalk_owner: 'lounlay'
  gitalk_admin: 'lounlay'
  distractionFreeMode: true




